//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauranteConstanTeamEntities : DbContext
    {
        public RestauranteConstanTeamEntities()
            : base("name=RestauranteConstanTeamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<ingredientes> ingredientes { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<platos> platos { get; set; }
        public virtual DbSet<platosPorPedido> platosPorPedido { get; set; }
    }
}
